### ISSUE TITLE
Axis of systematic factor_vector in multiplication with response matrix A

### ISSUE THREAD

**Issue by lwitthaus** [tudo-astroparticlephysics/funfolding#6]
I get an error `ValueError: operands could not be broadcast together with shapes (X,Y) (Y,1) (X,Y)` with X/Y as the number of observable/target bins when trying to perform an unfolding with additional systematic parameters. Apparently funfolding tries to multiply the `factor_vector` to the matrix `A` over the wrong axis in this line of code?

https://github.com/tudo-astroparticlephysics/funfolding/blob/2f485b04f8d79698527fcaab015baf708505e8dd/funfolding/model/_model.py#L1103

Or am I just using it wrong?

**Comment by maxnoe** [comment]
What's the solution?

**Comment by lwitthaus** [comment]
I made a mistake in defining my systematics. I did not use it correctly.
